/**
 * KATO — the Kazakh administrative-territorial classifier, as the address
 * cascade consumes it.
 *
 * Reference DATA, not domain knowledge: this module knows what an oblast is and
 * nothing about businesses, branches, offers or search (the §5 litmus test for
 * what may live in `shared/`). It is the same kind of tenant as `shared/i18n`'s
 * message catalogues — facts about the world the whole product renders, owned
 * by no slice.
 *
 * Platform-neutral and DOM-free (D5): pure data + pure functions, so it lifts
 * into a React Native package unchanged. The one impure edge is `loadLocalities`,
 * which is a dynamic `import()` — a bundler primitive, not a browser API, and
 * Metro implements it too.
 *
 * ── THE SHAPE OF THE REGISTRY, WHICH DRIVES THE WHOLE CASCADE ──────────────
 * Two kinds of region exist and they do NOT have the same depth:
 *
 *   oblast (17)            → districts → localities        (three questions)
 *   republican city (3)    → city districts                (two questions)
 *
 * Astana, Almaty and Shymkent sit at region level with no oblast above them and
 * carry no localities at all — which is why `REPUBLICAN_CITY_IDS` is a branch in
 * the UI rather than a cosmetic pin, and why `loadLocalities` answers them
 * without a request.
 *
 * An oblast ALSO owns localities directly (keyed `region_{id}`) — its cities and
 * villages that belong to no district. Those are offered in the SAME list as its
 * districts, because from the seller's side "Көкшетау қ." and "Ақкөл ауданы" are
 * the same question: where in this oblast are you.
 *
 * Data is generated by `scripts/build-kato.mjs`; that file documents the split
 * and why `code` is kept.
 */
import districtsData from "./districts.json";
import regionsData from "./regions.json";

/** One registry row. `id` is the export's surrogate key (what the maps are
 *  keyed by); `code` is the real KATO code, carried for reconciliation. */
export type KatoItem = {
  id: number;
  code: number;
  nameRus: string;
  nameKaz: string;
};

/** Astana, Almaty, Shymkent. Region-level, no localities, cascade stops at the
 *  city district. */
export const REPUBLICAN_CITY_IDS: ReadonlySet<number> = new Set([
  17108, 17112, 17211,
]);

const regions = regionsData as KatoItem[];
const districts = districtsData as Record<string, KatoItem[]>;

/** Every region — the 3 republican cities first, then the 17 oblasts. */
export function getRegions(): KatoItem[] {
  return regions;
}

export function isRepublicanCity(regionId: number | null | undefined): boolean {
  return regionId != null && REPUBLICAN_CITY_IDS.has(regionId);
}

/** A region's districts (city districts, for a republican city). */
export function getDistricts(regionId: number): KatoItem[] {
  return districts[String(regionId)] ?? [];
}

// ── Localities — one lazily-loaded chunk per region ─────────────────────────

/** A region's locality chunk: `region_{id}` → the oblast's own localities,
 *  `{districtId}` → the localities under that district. */
type LocalityChunk = Record<string, KatoItem[]>;

const EMPTY_CHUNK: LocalityChunk = {};

/** Resolved chunks, keyed by region. Module scope is safe here in a way a store
 *  never is (Rendering & State locks): this is immutable reference data with no
 *  per-request identity, so sharing it across SSR requests is the point rather
 *  than a leak. */
const chunkCache = new Map<number, Promise<LocalityChunk>>();

/**
 * Load one region's localities. ~24–145 KB, fetched at most once per region and
 * never at all for a republican city — the 1.1 MB of localities is the reason
 * this is async rather than a static import (see the build script's header).
 *
 * A failed chunk resolves to an empty map rather than throwing: a missing
 * settlement list must degrade to "the district is as specific as we can be",
 * not take down the form the seller is filling in.
 */
export function loadLocalities(regionId: number): Promise<LocalityChunk> {
  if (isRepublicanCity(regionId)) return Promise.resolve(EMPTY_CHUNK);
  const cached = chunkCache.get(regionId);
  if (cached) return cached;

  const pending = import(`./localities/${regionId}.json`)
    .then((module) => (module.default ?? module) as LocalityChunk)
    .catch(() => {
      // Evict, so a transient failure can be retried by the next selection
      // instead of caching the empty answer for the rest of the session.
      chunkCache.delete(regionId);
      return EMPTY_CHUNK;
    });
  chunkCache.set(regionId, pending);
  return pending;
}

/** The oblast's OWN localities — cities and villages under no district. */
export function regionLocalities(
  chunk: LocalityChunk,
  regionId: number,
): KatoItem[] {
  return chunk[`region_${regionId}`] ?? [];
}

/** The localities under one district. */
export function districtLocalities(
  chunk: LocalityChunk,
  districtId: number,
): KatoItem[] {
  return chunk[String(districtId)] ?? [];
}

// ── Display ─────────────────────────────────────────────────────────────────

/**
 * The registry name in the reader's language.
 *
 * KATO ships Russian and Kazakh only — there is no English column, so `en`
 * falls back to Russian. That is a data fact stated plainly rather than a
 * transliteration invented client-side (P9.4): a made-up Latin spelling of
 * "Ақмола облысы" would be a name no document, map or courier recognises.
 */
export function katoName(item: KatoItem, locale: string): string {
  return locale === "kk" ? item.nameKaz : item.nameRus;
}

/**
 * Whether a row is a CITY rather than a district or village — the registry
 * marks it in the name itself (`г. Кокшетау` / `Көкшетау қ.`) and nowhere else.
 *
 * Both spellings are checked regardless of the active locale, because the flag
 * decides ORDER, and the order must not change when the reader switches
 * language: a seller who found their city at the top in Kazakh must find it at
 * the top in Russian.
 */
export function isCity(item: KatoItem): boolean {
  return item.nameRus.startsWith("г.") || item.nameKaz.endsWith("қ.");
}

/**
 * Order a list for display: cities first, then everything else, each block
 * alphabetical in the reader's own language.
 *
 * Sorting is done HERE and not at build time precisely because it is
 * locale-dependent — `localeCompare` on Cyrillic orders Kazakh's ә/ғ/қ/ң/ө/ұ/ү/һ/і
 * differently from Russian, and a build-time order could only ever be right for
 * one of the three languages.
 */
export function orderForDisplay(items: KatoItem[], locale: string): KatoItem[] {
  const collator = new Intl.Collator(locale === "kk" ? "kk" : "ru");
  return [...items].sort((a, b) => {
    const aCity = isCity(a);
    const bCity = isCity(b);
    if (aCity !== bCity) return aCity ? -1 : 1;
    return collator.compare(katoName(a, locale), katoName(b, locale));
  });
}
